# Generated by Django 4.1.7 on 2023-03-23 19:37

import coloring.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0002_coloringpagetag_postpagecoloringcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloringpage',
            name='body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock()), ('h2', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image_text', wagtail.blocks.StructBlock([('reverse', wagtail.blocks.BooleanBlock(required=False)), ('text', wagtail.blocks.RichTextBlock()), ('image', coloring.blocks.CustomImageChooserBlock(rendition='width-800'))])), ('image_carousel', wagtail.blocks.ListBlock(coloring.blocks.CustomImageChooserBlock())), ('thumbnail_gallery', wagtail.blocks.ListBlock(coloring.blocks.CustomImageChooserBlock()))], blank=True, use_json_field=None),
        ),
    ]
