# Generated by Django 4.1.7 on 2023-04-04 22:03

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0003_alter_coloringpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoringGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.AddField(
            model_name='coloringpage',
            name='short_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
