# Generated by Django 4.1.7 on 2023-04-04 22:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0004_coloringgrade_coloringpage_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostColoringGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coloring_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colorin_pages', to='coloring.coloringgrade')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='coloring.coloringpage')),
            ],
            options={
                'unique_together': {('page', 'coloring_grade')},
            },
        ),
    ]
